version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    env_file:
      - ./stack.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:       ${DB_DATABASE}
      MYSQL_USER:           ${DB_USERNAME}
      MYSQL_PASSWORD:       ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - motos_net

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./stack.env
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    networks:
      - motos_net

    # <<< aquí montas tu código src vivo >>>
    volumes:
      - /share/docker/motos_app/src:/var/www/html:rw

    entrypoint: >
      sh -c "
        # asegúrate de que existan estas carpetas
        mkdir -p /var/www/html/storage/framework/{sessions,views,cache} \
                 /var/www/html/storage/logs \
                 /var/www/html/bootstrap/cache &&
        # corrige permisos para www-data
        chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
        # arranca el servidor
        php artisan serve --host=0.0.0.0 --port=8000
      "

networks:
  motos_net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /share/docker/motos_app/mariadb_data