services:

  mariadb:
    image: mariadb:latest
    # container_name: motos_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:       ${DB_DATABASE}
      MYSQL_USER:           ${DB_USERNAME}
      MYSQL_PASSWORD:       ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - motos_net

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: motos_laravel
    restart: always
    # env_file:
    #   - ./.env
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    ports:
      - 8000:8000
    networks:
      - motos_net

networks:
  motos_net:
    driver: bridge
    # external: true

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /share/CACHEDEV6_DATA/docker/motos_donosti/mariadb_data